apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: sinatra-kube-example
spec:
  maxReplicas: 10
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: sinatra-kube-example
  targetCPUUtilizationPercentage: 50
